### Create a new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "text": "hello comment",
  "postId": 1,
  "username": "s0t12"
}

### Create a new reply comment
POST http://localhost:3000/comments/1/replies
Content-Type: application/json

{
  "text": "Reply to parent comment",
  "postId": 1,
  "username": "s0t12"
}

### Get all comments
GET http://localhost:3000/comments

### Get a specific comment
GET http://localhost:3000/comments/1

### Update a comment
PATCH http://localhost:3000/comments/1
Content-Type: application/json

{
  "text": "Updated comment"
}

### Delete a comment
DELETE http://localhost:3000/comments/1