### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
	"username": "user123",
    "name": "user",
    "role": "user",
    "posts": []
}


### Get users
GET http://localhost:3000/users
    

### Get by id
GET http://localhost:3000/users/6


### Update user
PATCH http://localhost:3000/users/6
Content-Type: application/json

{
    "name": "s0t12",
    "role": "admin"
}

### Remove user
DELETE http://localhost:3000/users/14