### Create post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "s0t12",
    "text": "hello world",
    "author": 6,
    "category": ["Projects"]
}


### Get posts
GET http://localhost:3000/posts


### Get by id
GET http://localhost:3000/posts/1


### Update post
PATCH http://localhost:3000/posts/1
Content-Type: application/json

{
    "title": "chatApp",
    "text": "chatApp"
}


### Remove post
DELETE http://localhost:3000/posts/1


### Get by category
GET http://localhost:3000/posts/category/Projects