### get Token
POST http://localhost:3000/auth
Content-Type: application/json

{
    "username": "use",
    "password": "use"
}

### check
GET http://localhost:3000/auth/check
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhhc3NhbiIsInN1YiI6IjEyMyIsImlhdCI6MTY5MTg4MzYxNH0.0eK4t7eaIWAGAqL3Q29WBGt8yczg9O58_iLMOLmqkPI